package com.elite.vo;
// Generated 2017-7-5 11:41:52 by Hibernate Tools 3.5.0.Final


/**
 * OriginalData generated by hbm2java
 */
public class OriginalData implements java.io.Serializable {

	private Integer Id;
	private String serRdNumber;
	private String acceptNumber;
	private String skillQueue;
	private String workGroup;
	private String zuoxiNumber;
	private String serName;
	private String serNickname;
	private String visitWay;
	private String visitIp;
	private String ipProvice;
	private String businessType;
	private String clientRank;
	private String clientBrand;
	private String clientProvice;
	private String clientCity;
	private String conversationStartTime;
	private String conversationEndTime;
	private String conversationAssess;
	private String conversationTime;
	private String replyIntervalTime;
	private String satisfactionType;
	private String solveType;
	private String endPerson;
	private String endReason;
	private String clientSpeakFrequency;
	private String serSpeakFrequency;
	private String interactionFrequency;
	private String isvalidConversation;
	private String comment;
	private String conversationContent;
	private String robotConversationContent;
	private Integer keywordID;
	private String service;
	private String client;
	private String indexID;
	private String datatype;

	public OriginalData() {
	}

	public OriginalData(String serRdNumber, String acceptNumber, String skillQueue, String workGroup,
			String zuoxiNumber, String serName, String serNickname, String visitWay, String visitIp, String ipProvice,
			String businessType, String clientRank, String clientBrand, String clientProvice, String clientCity,
			String conversationStartTime, String conversationEndTime, String conversationAssess,
			String conversationTime, String replyIntervalTime, String satisfactionType, String solveType,
			String endPerson, String endReason, String clientSpeakFrequency, String serSpeakFrequency,
			String interactionFrequency, String isvalidConversation, String comment, String conversationContent,
			String robotConversationContent, Integer keywordID, String service, String client ,String indexID ,String datatype) {
		
		this.serRdNumber = serRdNumber;
		this.acceptNumber = acceptNumber;
		this.skillQueue = skillQueue;
		this.workGroup = workGroup;
		this.zuoxiNumber = zuoxiNumber;
		this.serName = serName;
		this.serNickname = serNickname;
		this.visitWay = visitWay;
		this.visitIp = visitIp;
		this.ipProvice = ipProvice;
		this.businessType = businessType;
		this.clientRank = clientRank;
		this.clientBrand = clientBrand;
		this.clientProvice = clientProvice;
		this.clientCity = clientCity;
		this.conversationStartTime = conversationStartTime;
		this.conversationEndTime = conversationEndTime;
		this.conversationAssess = conversationAssess;
		this.conversationTime = conversationTime;
		this.replyIntervalTime = replyIntervalTime;
		this.satisfactionType = satisfactionType;
		this.solveType = solveType;
		this.endPerson = endPerson;
		this.endReason = endReason;
		this.clientSpeakFrequency = clientSpeakFrequency;
		this.serSpeakFrequency = serSpeakFrequency;
		this.interactionFrequency = interactionFrequency;
		this.isvalidConversation = isvalidConversation;
		this.comment = comment;
		this.conversationContent = conversationContent;
		this.robotConversationContent = robotConversationContent;
		this.keywordID = keywordID;
		this.service = service;
		this.client = client;
		this.indexID = indexID;
		this.datatype = datatype;
	}
	
	
	
	public String getDatatype() {
		return datatype;
	}

	public void setDatatype(String datatype) {
		this.datatype = datatype;
	}

	public String getIndexID() {
		return indexID;
	}

	public void setIndexID(String indexID) {
		this.indexID = indexID;
	}

	public Integer getKeywordID() {
		return keywordID;
	}

	public void setKeywordID(Integer keywordID) {
		this.keywordID = keywordID;
	}

	public String getService() {
		return service;
	}

	public void setService(String service) {
		this.service = service;
	}

	public String getClient() {
		return client;
	}

	public void setClient(String client) {
		this.client = client;
	}

	public Integer getId() {
		return Id;
	}

	public void setId(Integer id) {
		Id = id;
	}

	public String getSerRdNumber() {
		return this.serRdNumber;
	}

	public void setSerRdNumber(String serRdNumber) {
		this.serRdNumber = serRdNumber;
	}

	

	public String getAcceptNumber() {
		return acceptNumber;
	}

	public void setAcceptNumber(String acceptNumber) {
		this.acceptNumber = acceptNumber;
	}

	public String getSkillQueue() {
		return this.skillQueue;
	}

	public void setSkillQueue(String skillQueue) {
		this.skillQueue = skillQueue;
	}

	public String getWorkGroup() {
		return this.workGroup;
	}

	public void setWorkGroup(String workGroup) {
		this.workGroup = workGroup;
	}

	public String getZuoxiNumber() {
		return this.zuoxiNumber;
	}

	public void setZuoxiNumber(String zuoxiNumber) {
		this.zuoxiNumber = zuoxiNumber;
	}

	public String getSerName() {
		return this.serName;
	}

	public void setSerName(String serName) {
		this.serName = serName;
	}

	public String getSerNickname() {
		return this.serNickname;
	}

	public void setSerNickname(String serNickname) {
		this.serNickname = serNickname;
	}

	public String getVisitWay() {
		return this.visitWay;
	}

	public void setVisitWay(String visitWay) {
		this.visitWay = visitWay;
	}

	public String getVisitIp() {
		return this.visitIp;
	}

	public void setVisitIp(String visitIp) {
		this.visitIp = visitIp;
	}

	public String getIpProvice() {
		return this.ipProvice;
	}

	public void setIpProvice(String ipProvice) {
		this.ipProvice = ipProvice;
	}

	public String getBusinessType() {
		return this.businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}

	public String getClientRank() {
		return this.clientRank;
	}

	public void setClientRank(String clientRank) {
		this.clientRank = clientRank;
	}

	public String getClientBrand() {
		return this.clientBrand;
	}

	public void setClientBrand(String clientBrand) {
		this.clientBrand = clientBrand;
	}

	public String getClientProvice() {
		return this.clientProvice;
	}

	public void setClientProvice(String clientProvice) {
		this.clientProvice = clientProvice;
	}

	public String getClientCity() {
		return this.clientCity;
	}

	public void setClientCity(String clientCity) {
		this.clientCity = clientCity;
	}

	public String getConversationStartTime() {
		return this.conversationStartTime;
	}

	public void setConversationStartTime(String conversationStartTime) {
		this.conversationStartTime = conversationStartTime;
	}

	public String getConversationEndTime() {
		return this.conversationEndTime;
	}

	public void setConversationEndTime(String conversationEndTime) {
		this.conversationEndTime = conversationEndTime;
	}

	public String getConversationAssess() {
		return this.conversationAssess;
	}

	public void setConversationAssess(String conversationAssess) {
		this.conversationAssess = conversationAssess;
	}

	public String getConversationTime() {
		return this.conversationTime;
	}

	public void setConversationTime(String conversationTime) {
		this.conversationTime = conversationTime;
	}

	public String getReplyIntervalTime() {
		return this.replyIntervalTime;
	}

	public void setReplyIntervalTime(String replyIntervalTime) {
		this.replyIntervalTime = replyIntervalTime;
	}

	public String getSatisfactionType() {
		return this.satisfactionType;
	}

	public void setSatisfactionType(String satisfactionType) {
		this.satisfactionType = satisfactionType;
	}

	public String getSolveType() {
		return this.solveType;
	}

	public void setSolveType(String solveType) {
		this.solveType = solveType;
	}

	public String getEndPerson() {
		return this.endPerson;
	}

	public void setEndPerson(String endPerson) {
		this.endPerson = endPerson;
	}

	public String getEndReason() {
		return this.endReason;
	}

	public void setEndReason(String endReason) {
		this.endReason = endReason;
	}

	public String getClientSpeakFrequency() {
		return this.clientSpeakFrequency;
	}

	public void setClientSpeakFrequency(String clientSpeakFrequency) {
		this.clientSpeakFrequency = clientSpeakFrequency;
	}

	public String getSerSpeakFrequency() {
		return this.serSpeakFrequency;
	}

	public void setSerSpeakFrequency(String serSpeakFrequency) {
		this.serSpeakFrequency = serSpeakFrequency;
	}

	public String getInteractionFrequency() {
		return this.interactionFrequency;
	}

	public void setInteractionFrequency(String interactionFrequency) {
		this.interactionFrequency = interactionFrequency;
	}

	public String getIsvalidConversation() {
		return this.isvalidConversation;
	}

	public void setIsvalidConversation(String isvalidConversation) {
		this.isvalidConversation = isvalidConversation;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getConversationContent() {
		return this.conversationContent;
	}

	public void setConversationContent(String conversationContent) {
		this.conversationContent = conversationContent;
	}

	public String getRobotConversationContent() {
		return this.robotConversationContent;
	}

	public void setRobotConversationContent(String robotConversationContent) {
		this.robotConversationContent = robotConversationContent;
	}

}
